= Test Center ICDL

== Link utili

Procedure Test Center:: https://www.aicanet.it/standard-di-qualita/procedure-per-i-test-center[https://www.aicanet.it/standard-di-qualita/procedure-per-i-test-center]
Procedure Candidati:: https://www.aicanet.it/standard-di-qualita/procedure-per-il-candidato[https://www.aicanet.it/standard-di-qualita/procedure-per-il-candidato]
Erogazione esami in remoto::  http://domino.aicanet.it/aica/sessiononline.nsf/login[ttp://domino.aicanet.it/aica/sessiononline.nsf/login]
Area Riservata Test Center:: http://domino.aicanet.it/aica/accredita.nsf[http://domino.aicanet.it/aica/accredita.nsf]
ATLAS:: https://download-atlas.aicanet.it/00home/home.html[https://download-atlas.aicanet.it/00home/home.html]
ATLAS ONLINE:: https://supporto-atlas.aicanet.it/Atlas-Online.html[https://supporto-atlas.aicanet.it/Atlas-Online.html] https://supporto-atlas.aicanet.it/Atlas-Online.html
AICE:: http://aiceapp.it/[http://aiceapp.it/]
AICA:: https://www.aicanet.it/[https://www.aicanet.it]
ICDL Italia:: https://www.ecdl.it/[https://www.ecdl.it/]

== 1 -- Accredia

* Ente italiano di accreditamento in attuazione di un regolamento europeo del 2008.
* ICDL Full Standard è lo schema di certificazione delle competenze informatiche
* L'accreditamento è una garanzia tra parti
* ICDL certifica le persone come **Utente Qualificato di Computer** (Qualified Computer User)
* Chi vuole avere la certificazione deve sottoscrivere un contratto di certificazione
* Il responsabile del Test Center deve inserire la sottoscrizione del contratto di certificazione nel sistema Atlas
* La skills card non scade mai ma gli esami devono essere superati entro 5 anni dalla data di effettuazione del primo esame
* Il certificato scade dopo 5 anni dalla data di emissione e può essere rinnovato (update)

== 2 -- Il supervisore

* Il Supervisore è la persona abilitata a presidiare una sessione di esami di certificazione in conseguenza di una formale qualificazione da parte di AICA
* È responsabile dell'organizzazione e della gestione della sessione di esami, dell'organizzazione tecnica degli esami automatici di certificazione, della sorveglianza (controllo della regolarità del loro svolgimento) e del supporto tecnico ai candidati
* Un esaminatore deve firmare una dichiarazione sull'assenza di conflitti di interesse
* Deve essere **scrupoloso** nella conoscenza e applicazione delle procedure AICA.
* Deve essere **attento** nei compiti di sorveglianza
* Deve essere **severo** nei confronti dei candidati che non rispettano quanto previsto dalle procedure
* Deve essere **fermo** nei confronti di pressioni esterne
* Si deve attenere ad un **codice di condotta**:
. Obbligo della **sorveglianza**
. **Non interferenza** sull'esito degli esami

=== Quiz

====
. La principale qualità di un Supervisore consiste nella conoscenza approfondita del sistema di erogazione automatica degli esami (ATES).

* [ ] Vero
* [X] Falso

. Tra le qualità principali di un Supervisore vi è la scrupolosa conoscenza delle norme previste da AICA.

* [X] Vero
* [ ] Falso

. Il Docente che prepara gli studenti agli esami di certificazione deve conoscere le procedure di esame ECDL.

* [ ] Vero
* [X] Falso

. Gli esami sostenuti ai fini della certificazione ECDL Full Standard, saranno considerati validi per il Supervisore solo se svolti presso un Test Center con una Ragione sociale diversa da quella del Test Center dove presta il suo operato.

* [X] Vero
* [ ] Falso

. Docente e Supervisore devono essere soggetti distinti

* [ ] Vero
* [X] Falso

. Il Supervisore si fa garante presso AICA del corretto comportamento tenuto dal Candidato.

* [X] Vero
* [ ] Falso

. Il Supervisore non deve mai interferire sull’esito degli esami.

* [X] Vero
* [ ] Falso

. Il Supervisore che ha rivestito il ruolo di Docente per i Candidati deve almeno mentalmente mantenere una netta distinzione tra le due attività.

* [X] Vero
* [ ] Falso

. E’ sempre preferibile che il ruolo di Docente rimanga distinto da quello di Supervisore.

* [X] Vero
* [ ] Falso

. Per garantire l’oggettività dell’esito dell’esame Il Supervisore deve far sì che il Candidato affronti la prova senza aiuti esterni di nessun tipo.

* [X] Vero
* [ ] Falso

. Per ogni sessione al Supervisore viene richiesta una Dichiarazione di assenza di conflitto di interessi ai sensi della norma ISO17024

* [ ] Vero
* [X] Falso

. Un buon Supervisore è consapevole di dover in primo luogo garantire l’oggettività dell’esito degli esami.

* [X] Vero
* [ ] Falso

. Il ruolo del Supervisore AICA si caratterizza per il particolare codice di condotta.

* [X] Vero
* [ ] Falso

. Il ruolo di Supervisore prevede il rispetto di uno specifico codice di comportamento.

* [X] Vero
* [ ] Falso

. Durante la sessione di esami, il Supervisore che ha svolto il ruolo di Docente può fare precisazioni su aspetti trascurati nella attività formativa.

* [ ] Vero
* [X] Falso
====

== Approntamento delle postazioni

. Provvedere all'approntamento delle postazioni di esami e del server del sistema ATES
. Prima dell'inizio di ogni sessione di esami
.. verificare il corretto funzionamento e la corretta configurazione delle attrezzature informatiche
.. verificare corretta installazione componenti sistema ATES
.. verificare che firewall e antivirus non interferiscano
.. verificare distanza (almeno 80 cm) o sistema di separazione per ridurre rischi di interazione tra candidati
. verificare che le postazioni siano libere da qualunque documentazione

====

. La corretta distanza tra le postazioni deve essere controllata dal Supervisore nel momento in cui vengono assegnate ai candidati

* [ ] Vero
* [X] Falso

. Prima che la sessione abbia inizio occorre accertarsi che altri software installati non interferiscano con il corretto funzionamento del sistema ATES (es. firewall
o antivirus)

* [X] Vero
* [ ] Falso

. Prima che la sessione abbia inizio il Supervisore deve rimuovere dalle postazioni l’eventuale documentazione che non appartiene al Test Center.

* [ ] Vero
* [X] Falso

. Prima che la sessione abbia inizio il Supervisore deve verificare il corretto funzionamento delle postazioni messe a disposizione dei candidati.

* [X] Vero
* [ ] Falso

. Per un efficace servizio di certificazione il Test Center, quando lo ritiene necessario, deve provvedere all’approntamento delle postazioni di esame

* [ ] Vero
* [X] Falso

. L’approntamento delle postazioni può essere delegata al tecnico di laboratorio, che se ne assume la piena responsabilità

* [ ] Vero
* [X] Falso

. Prima che la sessione abbia inizio il Supervisore deve verificare la corretta distanza tra le postazioni messe a disposizione dei candidati.

* [X] Vero
* [ ] Falso

. La disposizione a scacchiera delle postazioni può essere adottata stabilmente quando consente l’utilizzo del numero minimo previsto di PC

* [X] Vero
* [ ] Falso

. L’interposizione di divisori tra le postazioni è consigliato ai fini della privacy dei candidati

* [ ] Vero
* [X] Falso

. Nelle postazioni utilizzare per gli esami di certificazione deve essere installato solamente il software ATES

* [ ] Vero
* [X] Falso
====

== 4 -- Operazioni preliminari per l'accesso dei candidati

. Abilitazione delle postazioni di esame
.. accendere i PC
.. loggarsi
.. avviare il software ATES nella postazione docente e in quelle abilitate ai candidati
.. andare sulla schermata di login
. Compilazione del **registro esami**
.. Tutti i supervisiori firmano il registro stampato
.. Tutti i candidati presenti firmano il registro stampato
. Stampa del **verbale sessione di esami**
.. deve essere stampato contestualmente al registro esami
.. tutte le anomalie devono essere annotate
. Riconoscimento formale dei candidati
.. prima dell'accesso alla postazione il candidato deve essere riconosciuto mediante un documento di identità
.. se il candidato non ha un documento di identità può essere riconosciuto da due persone maggiorenni. In tal caso sul verbale della sessione devono essere registrati gli estremi dei documenti delle due persone maggiorenni e il motivo per il quale il supervisore ha valutato ammissibile il riconoscimento
.. il riconoscimento può essere delegato a personale di segreteria
.. gli estremi del documento sono annotati nel registro esami
.. il candidato firma il registro esami
. Comunicazione password d'accesso al sistema ATES
.. Prima dell'inizio della prima prova il supervisore comunica privatamente i dati di accesso
. Illustrazione della metodologia di esami
.. norme per i candidati, da far sottoscrivere
.. tutorial messi a disposizione da AICA
 .. il tutorial deve essere eseguito necessariamente anche il giorno precedente quello della prova di esame

====

. Una illustrazione delle modalità di svolgimento degli esami ECDL da parte del Supervisore, favorisce un corretto svolgimento della sessione.


* [X] Vero
* [ ] Falso

. Il riconoscimento formale del Candidato può essere effettuato da altro personale del Test Center purché il Supervisore affianchi la persona incaricata durante tale operazione.

* [ ] Vero
* [X] Falso

. Il Supervisore che presiede la sessione al termine dell’erogazione degli esami ECDL dovrà provvedere alla compilazione esaustiva del Registro Esami.

* [ ] Vero
* [X] Falso

. Ciascun Candidato deve firmare il registro Esami in corrispondenza dei propri dati identificativi, nel caso in cui intenda accettare l’esito conseguito nell’esame sostenuto.

* [ ] Vero
* [X] Falso

. Il Supervisore che dichiara nel Registro Esami di presiedere la Sessione, è responsabile dell’autenticità di quanto riportato nel documento


* [X] Vero
* [ ] Falso

. Prima di assegnare la postazione al candidato, il Supervisore deve avviare il software ATES, predisponendolo sulla schermata di login.

* [X] Vero
* [ ] Falso

. Il Registro Esami deve essere firmato dai Supervisori presenti e da tutti i Candidati che hanno sostenuto esami

* [X] Vero
* [ ] Falso

. Il Tutorial illustra al Candidato la metodologia e le modalità di svolgimento delle prove di esame.


* [X] Vero
* [ ] Falso

. Nel Verbale di sessione debbono essere annotate tutte le anomalie degne di nota, che si sono verificate durante la sessione

* [X] Vero
* [ ] Falso

. Il Supervisore deve informare i candidati dell’importanza delle norme che regolano lo svolgimento degli esami che devono essere da questi sottoscritte.

* [X] Vero
* [ ] Falso

. Il riconoscimento formale del candidato può avvenire anche per conoscenza personale del Supervisore (ad esempio, alunno interno)

* [ ] Vero
* [X] Falso

. Per ogni aula utilizzata per lo svolgimento degli esami ECDL deve essere predisposto uno specifico Registro Esami.

* [X] Vero
* [ ] Falso

. Prima dell’inizio della prima prova d’esame il Supervisore comunicherà privatamente a ciascun candidato i dati di login necessari per accedere al sistema ATES.

* [X] Vero
* [ ] Falso

. Nessun Candidato può iniziare la prima prova di esame ECDL di una sessione senza essere stato preventivamente identificato formalmente.

* [X] Vero
* [ ] Falso

. Il riconoscimento formale del Candidato deve avvenire tramite apposito documento che ne attesti l’identità.

* [X] Vero
* [ ] Falso
====


== 5 -- Norme per supervisiori e candidati

* Obblighi del supervisiore per oggettività e imparzialità
** sorveglianza della sessione di esami
*** il supervisore non deve svolgere altre attività durante la sorveglianza
*** il supervisore non deve arrecare disturbo ai candidati
** gestione della sessione di esami
*** divieto di interrompere la sorveglianza degli esami in corso
*** possibilità di dividere la sessione in turni
*** obbligo di rimanere presso il Test Center
** divieto di assistere i candidati nella soluzione dei quesiti
*** divieto di rispondere alle domande dei candidati
*** permesso di intervento solo per problemi di operatività
** rispetto dell'orario
*** prove iniziate prima dell'inizio o terminate dopo l'orario di fine sono invalide
* Obblighi dei candidati
** obbligo di sottoscrizione del documento di assunzione di responsabilità
** obbligo di esecuzione del Tutorial
** soglia di superamento della prova d'esame
*** il candidato può richiedere l'annullamento della prova se non soddisfatto della valutazione
** rispetto dei limiti di tempo
** obbligo del silenzio
*** non parlare tra candidati
*** non ragionare ad alta voce
*** non rivolgere domande al supervisore se non per problemi di operatività
** divieto di supporti esterni
*** non copiare da altri candidati
*** non deve copiare da materiale cartaceo
*** non deve usare cellulari, tablet, radio o altri dispositivi elettronici
** permanenza in aula
*** il candidato permane in aula solo per il riconoscimento, lo svolgimento delle prove, la comunicazione dell'esito
** divieto di interruzione della prova
** divieto di ripetizione di un esame nella stessa giornata
** Divieto di assistere i candidati nella soluzione dei quesiti
** Controllo dell'ora di inizio e di fine

====
. Il Supervisore dovrà astenersi dal fornire al Candidato qualsiasi delucidazione sulle domande che costituiscono la prova di esame ECDL.

* [X] Vero
* [ ] Falso

. Ciascun candidato prima di affrontare la prima prova di esame deve prendere visione ed accettare le norme relative allo svolgimento degli esami

* [X] Vero
* [ ] Falso

. Il Candidato può rimanere in aula una volta completate le prove di esame a condizione che non arrechi disturbo agli altri 

* [ ] Vero
* [X] Falso

. Con un solo Supervisore in aula, la comunicazione al Candidato dell’esito della prova di esame rappresenta il momento favorevole per procedere alla revisione delle domande errate.

* [ ] Vero
* [X] Falso

. Scopo della sorveglianza effettuata dal Supervisore durante lo svolgimento di esami ECDL è evitare la presenza di persone che possano risultare estranee al Test Center o ai Candidati.

* [ ] Vero
* [X] Falso

. Senza la presenza di almeno un Supervisore qualificato da AICA, la sessione di esami deve essere annullata o interrotta.

* [X] Vero
* [ ] Falso

. Il Supervisore può comunicare al Candidato l’esito dopo ogni singola prova solo se ciò è compatibile con le esigenze di sorveglianza della sessione di esami.

* [X] Vero
* [ ] Falso

. Durante lo svolgimento di una prova di esame ECDL, il Supervisore non può intervenire su richiesta del Candidato neppure in caso di problemi connessi all’operatività della postazione.

* [ ] Vero
* [X] Falso

. Tra gli obblighi che il Candidato sottoscrive di rispettare durante lo svolgimento di una prova di esame ECDL, vi è quello del limite di tempo concesso per quell’esame.

* [X] Vero
* [ ] Falso

. Se il Supervisore incaricato di presiedere la sessione di esami ECDL non può essere presente, il Test Center deve tempestivamente richiedere l’intervento dell’Ispettore AICA.

* [ ] Vero
* [X] Falso

. Per una migliore riuscita di una sessione di esami ECDL è opportuno che il Test Center pianifichi l’ingresso dei Candidati per turni.

* [X] Vero
* [] Falso

. Al Supervisore è fatto obbligo di rispettare integralmente i comportamenti previsti dalla pertinente Procedura AICA.

* [X] Vero
* [ ] Falso

. Il Supervisore non deve in nessun caso interferire con il Candidato durante lo svolgimento di una prova di esame ECDL.

* [X] Vero
* [ ]Falso

. Il Candidato che ha fallito una prova di esame non può ripeterla nello stesso giorno, a meno che ciò non avvenga presso un diverso Test Center.

* [ ] Vero
* [X] Falso

. Il divieto di parlare e fare rumore facilità la possibilità per i Candidati di concentrarsi sulla propria prova di esame.

* [X] Vero
* [ ] Falso
====

== 6. 

====
. Qualora il Candidato rimanga insoddisfatto dell’esito della prova di esame deve presentare ricorso ad AICA

* [ ] Vero
* [X] Falso

. Entro 15 gg dalla data in cui ha sostenuto l’esame, il candidato può richiedere chiarimenti in merito alle domande a cui non ha fornito una risposta corretta.

* [X] Vero
* [ ] Falso

. Il Test Center comunicherà via mail al candidato, entro 15 gg, l’esito delle prove di esame

* [ ] Vero
* [X] Falso

. Nel caso in cui il candidato voglia ripetere l’esame superato, deve iscriversi ad una sessione presso un diverso Test Center

* [ ] Vero
* [X] Falso

. In argomento alle prove di esame ECDL, l’esito di un ricorso inoltrato dal Test Center verrà reso noto da AICA all’interessato prima che questi concluda il percorso di certificazione.


* [ ] Vero
* [X] Falso

. Una volta superate tutte le prove di esame, entro 15gg il Candidato deve inoltrare istanza scritta ad AICA per il rilascio della relativa certificazione.


* [ ] Vero
* [X] Falso


. In assenza di registrazione via Internet degli esami, il Supervisore può richiedere ad AICA via mail il rilascio del certificato

* [ ] Vero
* [X] Falso

. La registrazione degli esami può anche avvenire inviando ad AICA un prospetto cartaceo dei risultati conseguiti dai Candidati, sottoscritto dal legale Rappresentante.

* [ ] Vero
* [X] Falso

. Per la riservatezza delle domande di esame, la correzione delle domande errate a favore del Candidato può essere effettuata in presenza di altri Candidati solo se questi hanno già superato lo stesso esame.

* [ ] Vero
* [X] Falso

. La registrazione degli esami tramite sincronizzazione via Internet deve essere effettuata non oltre 5 giorni dalla data della sessione.

* [X] Vero
* [ ] Falso

. Una volta terminata la sessione di esami ECDL, il Supervisore provvede a registrare via Internet (sincronizzazione) i risultati delle prove di esame sul database di AICA

* [X] Vero
* [ ] Falso

. In argomento alle prove di esame ECDL, le circostanze e le motivazioni che rendono ammissibile un ricorso ad AICA da parte del Test Center sono esplicitate in apposite istruzioni operative.

* [X] Vero
* [ ] Falso

. Non appena completata la valutazione automatica di tutti gli esami sostenuti, e comunque entro la fine della sessione, al candidato devono essere comunicati gli esiti riservatamente.

* [X] Vero
* [ ] Falso

. Al termine di ogni sessione sarà cura di AICA comunicare al Test Center eventuali anomalie intervenute nella sincronizzazione dati con il database centralizzato.

* [ ] Vero
* [X] Falso

. E’ compito del Supervisore, riservatamente, fornire a ciascun Candidato che ne faccia richiesta chiarimenti in merito alle domande errate, servendosi dell’apposita funzionalità disponibile nel sistema ATES.

* [X] Vero
* [ ] Falso
====
